name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 변경이 있을 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 저장소 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Hugo 설치
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    # 3. 정적 사이트 빌드
    - name: Build site
      run: hugo --minify

    # 4. GitHub Pages 배포 저장소에 빌드 결과물 복사 및 배포
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: username/username.github.io # 배포용 저장소
        publish_branch: main # 배포용 저장소의 브랜치
        publish_dir: ./public
